```javascript
let promise = new Promise(function(resolve, reject){
	// функция-исполнитель (executor)
	resolve("done") /*или*/ reject(new Error("error"))
})
promise
	.then(()=>{})
	.catch(()=>{})
	.finally(()=>{})
```

Аргументы - колбэки функции:
- `resolve(value)` - eсли работа завершилась успешно,  с результатом `value`.
- `reject(error)` - если произошла ошибка, `error` - объект ошибки

Методы Promise:
- `.then((resolve)=>{})` - будет выполнена функция, если работа завершилась успешно. Так же можно передавать значение переданное в `resolve`.
- `.catch((reject)=>{})` - будет выполнена функция, если работа завершилась с ошибкой. Так же может передавать значение переданное в `reject`.
- `.finally(()=>{})`- будет выполнена функция, после сработки любого исхода.

У объекта promise, есть внутренние свойства:
- state (`"состояние"`) - вначале `"pending"`(`"ожидание"`), потом `"fulfilled"`(`"Выполненно успешно"`) при вызове ___resolve___ или `"rejected"`(`"Выполнено с ошибкой"`) при вызове ___reject___.
- result (`"результат"`) - вначале `"undefined"`, далее изменится на `"value"` при вызову ___resolve(value)___ или на `"error"` при вызову ___reject(error)___.
![[Pasted image 20241212083837.png]]

Исполнитель должен вызвать что-то одно: `resolve` или `reject`. Состояние Promise может быть изменено только один раз. Последующее вызов `resolve` или `reject` будет игнорирован.


[Javascript](Javascript)
